server:
  port: 8534
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json
endpoints:
  prometheus:
    sensitive: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,refresh
  metrics:
    enabled: true
    tags:
      application: ${spring.application.name}
spring:
  jackson.deserialization.fail_on_unknown_properties: false
ocs:
  connection-configuration:
    hosts: ${ES_HOSTS:http://localhost:9200}
    auth: ${ES_AUTH}
    ocs: null
  default-tenant-config:
    facet-configuration:
      maxFacets: 12
      facets:
        - source-field: category
          label: Category
          order: 1
          excludeFromFacetLimit: true
        - label: Hallo Welt
          source-field: brand
          multi-select: true
          order: 2
          excludeFromFacetLimit: true
          meta-data: {}
        - source-field: price
          label: Price
          order: 3
          show-unselected-options: true
          meta-data:
            unit: €
          excludeFromFacetLimit: true
        - source-field: size
          label: Size
          order: 4
          meta-data:
            detail-links: 5
          excludeFromFacetLimit: true
        - source-field: color
          label: Color
          multi-select: true
    scoring-configuration:
      boost-mode: avg
      score-mode: sum
      score-functions:
        - type: field_value_factor
          field: stock
          weight: 2.5
          options:
            missing: 0
    query-configuration:
      ean-search:
        strategy: ConfigurableQuery
        condition:
          matchingRegex: \s*\d{13}\s*(\s+\d{13})*
          maxTermCount: 42
        settings:
          operator: OR
          tieBreaker: 0
          analyzer: whitespace
          allowParallelSpellcheck: false
          acceptNoResult: true
        weightedFields:
          "[ean]": 1
      art-nr-search:
        strategy: ConfigurableQuery
        condition:
          matchingRegex: \s*(\d+\w?\d+\s*)+
          maxTermCount: 42
        settings:
          operator: OR
          tieBreaker: 0
          analyzer: whitespace
          allowParallelSpellcheck: false
          acceptNoResult: true
        weightedFields:
          "[artNr]": 2
          "[masterNr]": 1.5
      default-query:
        strategy: ConfigurableQuery
        condition:
          minTermCount: 1
          maxTermCount: 10
        settings:
          operator: AND
          tieBreaker: 0.7
          multimatch_type: CROSS_FIELDS
          analyzer: standard
          quoteAnalyzer: minimal
          isQueryWithShingles: true
          allowParallelSpellcheck: false
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category_leaf]": 2
          "[category_leaf.standard]": 1.7
          "[category_lvl_0]": 1
          "[category_lvl_0.standard]": 0.7
          "[category_lvl_1]": 1.1
          "[category_lvl_1.standard]": 0.8
          "[category_lvl_2]": 1.2
          "[category_lvl_2.standard]": 0.9
          "[category_lvl_3]": 1.3
          "[category_lvl_3.standard]": 1
      relaxed-query:
        strategy: RelaxedQuery
        condition:
          minTermCount: 2
          maxTermCount: 10
        settings:
          analyzer: standard
          fallbackQuery: relaxed-ngram-query
          tieBreaker: 0.2
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category_leaf]": 1.8
          "[category_leaf.standard]": 1.7
          "[category_lvl_0]": 1
          "[category_lvl_0.standard]": 0.7
          "[category_lvl_1]": 1.1
          "[category_lvl_1.standard]": 0.8
          "[category_lvl_2]": 1.2
          "[category_lvl_2.standard]": 0.9
          "[category_lvl_3]": 1.3
          "[category_lvl_3.standard]": 1
      one-term-fuzzy-search:
        strategy: ConfigurableQuery
        condition:
          maxTermCount: 1
        settings:
          tieBreaker: 0.7
          acceptNoResult: false
          allowParallelSpellcheck: false
          fuzziness: AUTO
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[category_leaf]": 1.8
          "[category_lvl_0]": 1
          "[category_lvl_1]": 1.1
          "[category_lvl_2]": 1.2
          "[category_lvl_3]": 1.3
      relaxed-ngram-query:
        strategy: NgramQuery
        condition:
          maxTermCount: 10
        settings:
          minShouldMatch: 80%
          tieBreaker: 0.2
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[category_leaf]": 2
          "[category_lvl_0]": 1
          "[category_lvl_1]": 1.1
          "[category_lvl_2]": 1.2
          "[category_lvl_3]": 1.3
      dismax-query:
        strategy: DisMaxQuery
        condition:
          minTermCount: 3
          matchingRegex: ^(\S+\s+){2,}\S{1,4}$
        weightedFields:
          "[title]": 1
          "[brand]": 1
      fallback-search:
        strategy: ConfigurableQuery
        condition:
          minTermCount: 10
        settings:
          analyzer: standard
          minShouldMatch: 75%
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category_leaf]": 2
          "[category_leaf.standard]": 1.7
          "[category_lvl_0]": 1
          "[category_lvl_0.standard]": 0.7
          "[category_lvl_1]": 1.1
          "[category_lvl_1.standard]": 0.8
          "[category_lvl_2]": 1.2
          "[category_lvl_2.standard]": 0.9
          "[category_lvl_3]": 1.3
          "[category_lvl_3.standard]": 1
