server:
  port: 8534
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json

endpoints:
  prometheus:
    sensitive: true

management:  
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  metrics:
    enabled: true
    tags:
      application: "${spring.application.name}"

spring:
  jackson.deserialization.fail_on_unknown_properties: false

ocs:
  connection-configuration:
    hosts: ${ES_HOSTS:http://localhost:9200}
    auth: ${ES_AUTH}
  default-tenant-config:
    facet-configuration:
      maxFacets: 12
      facets:
        - source-field: category
          label: Category
          order: 1
          excludeFromFacetLimit: true
        - source-field: brand
          label: Brand
          order: 2
          multi-select: true
          excludeFromFacetLimit: true
        - source-field: price
          label: Price
          order: 3
          show-unselected-options: true
          meta-data:
            unit: "€"
          excludeFromFacetLimit: true
        - source-field: size
          label: Size
          order: 4
          meta-data:
            detail-links: 5
          excludeFromFacetLimit: true
        - source-field: color
          label: Color
          multi-select: true
    scoring-configuration:
      boost-mode: avg
      score-mode: sum
      score-functions:
        - type: field_value_factor
          field: stock
          weight: 2.5
          options:
            missing: 0
    query-configuration:
      dismax-query:
        strategy: "DisMaxQuery"
        condition:
          minTermCount: 3
          matchingRegex: "^(\\S+\\s+){2,}\\S{1,4}$" # 3 or more words & last word must have less than 5 characters
        weightedFields:
          "[title]": 1
          "[brand]": 1
      # for all queries with more then 10 words
      fallback-search:
        strategy: "ConfigurableQuery"
        condition:
          minTermCount: 10
        settings:
          analyzer: "standard"
          minShouldMatch: "75%"
        weightedFields:
          "[title]": 3
          "[title.standard]": 2.5
          "[brand]": 2
          "[brand.standard]": 1.5
          "[category_leaf]": 2
          "[category_leaf.standard]": 1.7
          "[category_lvl_0]": 1
          "[category_lvl_0.standard]": 0.7
          "[category_lvl_1]": 1.1
          "[category_lvl_1.standard]": 0.8
          "[category_lvl_2]": 1.2
          "[category_lvl_2.standard]": 0.9
          "[category_lvl_3]": 1.3
          "[category_lvl_3.standard]": 1
